### ISSUE TITLE
Préparation de l'environnement

### ISSUE THREAD

**Issue by mdzoubir** [mdzoubir/C2N3#1]
Préparer le terrain pour un flux de travail Organizer, un code réutilisable et des tâches automatisées

 

- [x] git clone /lien Repository/ ou Fork
- [x] npm install /packages/
- [x] Watching concatenation Préfixage avec NPM Scripts
- [x] Compression du CSS et Javascript avec NPM Scripts

**Comment by youssefbm** [comment]
Le préfixage ne marche pas bien. Contactez vos collègue qui ont participé dans ma veille pour voir la sollution.

**Comment by mdzoubir** [comment]
@youssefbm jais traiter le problème de préfixe , regarde la résulta

**Comment by youssefbm** [comment]
Good
